# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Useless twisting of a new technology
email: bmcmenamin@gmail.com
description: This is the site to shame me into cleaning up my repo.
#paginate: 3
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bmcmenamin.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  bmcmenamin
linkedin: https://www.linkedin.com/in/bmcdata

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate]